name: Bug report
description: Report a bug in pal
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what actually happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Include the folder layout and commands you ran.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14.5 / Ubuntu 24.04 / Windows 11
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: 3.11.9
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output / logs
      render: shell
